In [ ]:
# Insurance Analytics Project

### Notebook 01: Data Profiling & Data Quality Assessment

## Objective:

# Understand dataset structure
# Assess data quality
# Identify missing values
# Identify duplicates
# Validate business rules
# Generate profiling summary

# Author: Chetan Sakate

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [19]:
excel_file = pd.ExcelFile(r"C:\Users\ACER\Documents\ExcelR Projects\Insurance Project\Insurance_Analytics_Project\data\raw\Policy Data.xlsx")

print(excel_file.sheet_names)

['Customer Information', 'Policy Details', 'Claims', 'Payment History', 'Additional Fields']

In [20]:
for sheet in excel_file.sheet_names:
    
    temp = pd.read_excel(
        file_path,
        sheet_name=sheet
    )

    print("\n")
    print("="*50)
    print(sheet)
    print("="*50)

    print(temp.columns.tolist())

==================================================
Customer Information
==================================================
['Customer ID', 'Name', 'Gender', 'Age', 'Occupation', 'Marital Status', 'Address (City, State, Zip Code)']


==================================================
Policy Details
==================================================
['Policy ID', 'Policy Type', 'Coverage Amount', 'Premium Amount', 'Policy Start Date', 'Policy End Date', 'Payment Frequency', 'Status', 'Customer ID']


==================================================
Claims
==================================================
['Claim ID', 'Date of Claim', 'Claim Amount', 'Claim Status', 'Reason for Claim', 'Settlement Date', 'Policy ID']


==================================================
Payment History
==================================================
['Payment ID', 'Date of Payment', 'Amount Paid', 'Payment Method', 'Payment Status', 'Policy ID']


==================================================
Additional Fields
==================================================
['Agent ID', 'Renewal Status', 'Policy Discounts', 'Risk Score', 'Policy ID']

In [21]:
import pandas as pd

file_path = "../data/raw/Policy Data.xlsx"

customer_df = pd.read_excel(
    file_path,
    sheet_name="Customer Information"
)

policy_df = pd.read_excel(
    file_path,
    sheet_name="Policy Details"
)

claims_df = pd.read_excel(
    file_path,
    sheet_name="Claims"
)

payment_df = pd.read_excel(
    file_path,
    sheet_name="Payment History"
)

additional_df = pd.read_excel(
    file_path,
    sheet_name="Additional Fields"
)

In [22]:
datasets = {
    "Customer": customer_df,
    "Policy": policy_df,
    "Claims": claims_df,
    "Payments": payment_df,
    "Additional": additional_df
}

In [23]:
for name, data in datasets.items():

    print("\n" + "="*60)
    print(name)
    print("="*60)

    print("Rows :", data.shape[0])
    print("Columns :", data.shape[1])

    print("\nData Types")
    print(data.dtypes)

    print("\nMissing Values")
    print(data.isnull().sum())

    print("\nDuplicates")
    print(data.duplicated().sum())

============================================================
Customer
============================================================
Rows : 5000
Columns : 7

Data Types
Customer ID                        object
Name                               object
Gender                             object
Age                                 int64
Occupation                         object
Marital Status                     object
Address (City, State, Zip Code)    object
dtype: object

Missing Values
Customer ID                        0
Name                               0
Gender                             0
Age                                0
Occupation                         0
Marital Status                     0
Address (City, State, Zip Code)    0
dtype: int64

Duplicates
0

============================================================
Policy
============================================================
Rows : 5000
Columns : 9

Data Types
Policy ID                    object
Policy Type                  object
Coverage Amount               int64
Premium Amount              float64
Policy Start Date    datetime64[ns]
Policy End Date      datetime64[ns]
Payment Frequency            object
Status                       object
Customer ID                  object
dtype: object

Missing Values
Policy ID            0
Policy Type          0
Coverage Amount      0
Premium Amount       0
Policy Start Date    0
Policy End Date      0
Payment Frequency    0
Status               0
Customer ID          0
dtype: int64

Duplicates
0

============================================================
Claims
============================================================
Rows : 5000
Columns : 7

Data Types
Claim ID                    object
Date of Claim       datetime64[ns]
Claim Amount                 int64
Claim Status                object
Reason for Claim            object
Settlement Date     datetime64[ns]
Policy ID                   object
dtype: object

Missing Values
Claim ID               0
Date of Claim          0
Claim Amount           0
Claim Status           0
Reason for Claim       0
Settlement Date     1555
Policy ID              0
dtype: int64

Duplicates
0

============================================================
Payments
============================================================
Rows : 5000
Columns : 6

Data Types
Payment ID                 object
Date of Payment    datetime64[ns]
Amount Paid               float64
Payment Method             object
Payment Status             object
Policy ID                  object
dtype: object

Missing Values
Payment ID         0
Date of Payment    0
Amount Paid        0
Payment Method     0
Payment Status     0
Policy ID          0
dtype: int64

Duplicates
0

============================================================
Additional
============================================================
Rows : 5000
Columns : 5

Data Types
Agent ID            object
Renewal Status      object
Policy Discounts     int64
Risk Score           int64
Policy ID           object
dtype: object

Missing Values
Agent ID            0
Renewal Status      0
Policy Discounts    0
Risk Score          0
Policy ID           0
dtype: int64

Duplicates
0

In [24]:
# Relationship Assessment

customer_df["Customer ID"].nunique()

5000

In [25]:
customer_df["Customer ID"].nunique()

5000

In [28]:
# Business Validation Rules

invalid_age = customer_df[
    (customer_df["Age"] < 18)
    |
    (customer_df["Age"] > 100)
]

In [29]:
customer_df["Gender"].value_counts()

Gender
Male      1705
Other     1655
Female    1640
Name: count, dtype: int64

In [30]:
policy_df[
    policy_df["Coverage Amount"] <= 0
]

Empty DataFrame
Columns: [Policy ID, Policy Type, Coverage Amount, Premium Amount, Policy Start Date, Policy End Date, Payment Frequency, Status, Customer ID]
Index: []

In [31]:
policy_df[
    policy_df["Premium Amount"] <= 0
]

Empty DataFrame
Columns: [Policy ID, Policy Type, Coverage Amount, Premium Amount, Policy Start Date, Policy End Date, Payment Frequency, Status, Customer ID]
Index: []

In [32]:
policy_df[
    policy_df["Policy Start Date"] >
    policy_df["Policy End Date"]
]

Empty DataFrame
Columns: [Policy ID, Policy Type, Coverage Amount, Premium Amount, Policy Start Date, Policy End Date, Payment Frequency, Status, Customer ID]
Index: []

In [33]:
claims_df[
    claims_df["Claim Amount"] < 0
]

Empty DataFrame
Columns: [Claim ID, Date of Claim, Claim Amount, Claim Status, Reason for Claim, Settlement Date, Policy ID]
Index: []

In [34]:
claims_df[
    claims_df["Settlement Date"] <
    claims_df["Date of Claim"]
]

Empty DataFrame
Columns: [Claim ID, Date of Claim, Claim Amount, Claim Status, Reason for Claim, Settlement Date, Policy ID]
Index: []

In [35]:
additional_df[
    (additional_df["Risk Score"] < 0)
    |
    (additional_df["Risk Score"] > 100)
]

Empty DataFrame
Columns: [Agent ID, Renewal Status, Policy Discounts, Risk Score, Policy ID]
Index: []

In [36]:
additional_df[
    additional_df["Policy Discounts"] < 0
]

Empty DataFrame
Columns: [Agent ID, Renewal Status, Policy Discounts, Risk Score, Policy ID]
Index: []

In [37]:
customer_df.shape
policy_df.shape
claims_df.shape
payment_df.shape
additional_df.shape

(5000, 5)

In [38]:
customer_df["Customer ID"].nunique()
policy_df["Customer ID"].nunique()
policy_df["Policy ID"].nunique()
claims_df["Policy ID"].nunique()
payment_df["Policy ID"].nunique()
additional_df["Policy ID"].nunique()

5000

In [39]:
print(customer_df.shape)
print(policy_df.shape)
print(claims_df.shape)
print(payment_df.shape)
print(additional_df.shape)

(5000, 7)
(5000, 9)
(5000, 7)
(5000, 6)
(5000, 5)

In [40]:
print(policy_df["Policy ID"].nunique())

print(claims_df["Policy ID"].nunique())

print(payment_df["Policy ID"].nunique())

print(additional_df["Policy ID"].nunique())

5000
3162
3158
5000

In [41]:
print(
    policy_df["Policy ID"].duplicated().sum()
)

print(
    claims_df["Policy ID"].duplicated().sum()
)

print(
    payment_df["Policy ID"].duplicated().sum()
)

print(
    additional_df["Policy ID"].duplicated().sum()
)

0
1838
1842
0

In [42]:
# Relationship Assessment

claims_per_policy = claims_df.groupby(
    "Policy ID"
)["Claim ID"].count()

claims_per_policy.describe()

count    3162.000000
mean        1.581278
std         0.807199
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         6.000000
Name: Claim ID, dtype: float64

In [43]:
payments_per_policy = payment_df.groupby(
    "Policy ID"
)["Payment ID"].count()

payments_per_policy.describe()

count    3158.000000
mean        1.583281
std         0.804957
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         6.000000
Name: Payment ID, dtype: float64

In [44]:
claims_per_policy.sort_values(
    ascending=False
).head(10)

Policy ID
POL73709176    6
POL46408344    6
POL97188917    5
POL76172999    5
POL64494784    5
POL77315241    5
POL69697487    5
POL61660074    5
POL85437892    5
POL55036826    5
Name: Claim ID, dtype: int64

In [45]:
payments_per_policy.sort_values(
    ascending=False
).head(10)

Policy ID
POL86299537    6
POL83165381    6
POL31178570    5
POL98604785    5
POL13070623    5
POL73942123    5
POL12925982    5
POL09615361    5
POL24211829    5
POL88709617    5
Name: Payment ID, dtype: int64

In [46]:
customer_df.isnull().sum()

policy_df.isnull().sum()

claims_df.isnull().sum()

payment_df.isnull().sum()

additional_df.isnull().sum()

Agent ID            0
Renewal Status      0
Policy Discounts    0
Risk Score          0
Policy ID           0
dtype: int64

In [47]:
print("CUSTOMER")
print(customer_df.isnull().sum())

print("\nPOLICY")
print(policy_df.isnull().sum())

print("\nCLAIMS")
print(claims_df.isnull().sum())

print("\nPAYMENTS")
print(payment_df.isnull().sum())

print("\nADDITIONAL")
print(additional_df.isnull().sum())

CUSTOMER
Customer ID                        0
Name                               0
Gender                             0
Age                                0
Occupation                         0
Marital Status                     0
Address (City, State, Zip Code)    0
dtype: int64

POLICY
Policy ID            0
Policy Type          0
Coverage Amount      0
Premium Amount       0
Policy Start Date    0
Policy End Date      0
Payment Frequency    0
Status               0
Customer ID          0
dtype: int64

CLAIMS
Claim ID               0
Date of Claim          0
Claim Amount           0
Claim Status           0
Reason for Claim       0
Settlement Date     1555
Policy ID              0
dtype: int64

PAYMENTS
Payment ID         0
Date of Payment    0
Amount Paid        0
Payment Method     0
Payment Status     0
Policy ID          0
dtype: int64

ADDITIONAL
Agent ID            0
Renewal Status      0
Policy Discounts    0
Risk Score          0
Policy ID           0
dtype: int64

In [49]:
customer_df["Gender"].value_counts()

Gender
Male      1705
Other     1655
Female    1640
Name: count, dtype: int64

In [50]:
customer_df["Marital Status"].value_counts()

Marital Status
Divorced    1289
Married     1255
Single      1234
Widowed     1222
Name: count, dtype: int64

In [51]:
policy_df["Status"].value_counts()

Status
Active        1682
Terminated    1678
Lapsed        1640
Name: count, dtype: int64

In [52]:
claims_df["Claim Status"].value_counts()

Claim Status
Approved    1712
Pending     1650
Denied      1638
Name: count, dtype: int64

In [53]:
payment_df["Payment Status"].value_counts()

Payment Status
Successful    2516
Failed        2484
Name: count, dtype: int64

In [54]:
additional_df["Renewal Status"].value_counts()

Renewal Status
Not Renewed    1685
Renewed        1668
Pending        1647
Name: count, dtype: int64

In [55]:
additional_df["Risk Score"].describe()

count    5000.000000
mean       50.384600
std        29.011857
min         1.000000
25%        26.000000
50%        51.000000
75%        75.250000
max       100.000000
Name: Risk Score, dtype: float64

In [56]:
pd.crosstab(
    claims_df["Claim Status"],
    claims_df["Settlement Date"].isnull()
)

Settlement Date  False  True
Claim Status
Approved          1201    511
Denied            1098    540
Pending           1146    504

In [57]:
def risk_bucket(score):
    
    if score <= 30:
        return "Low Risk"
    
    elif score <= 60:
        return "Medium Risk"
    
    else:
        return "High Risk"