In [1]:
import pandas as pd
import numpy as np

insurance_master = pd.read_csv(
    "../data/processed/insurance_master_dataset.csv"
)

claims_fact = pd.read_csv(
    "../data/processed/claims_fact.csv"
)

payment_fact = pd.read_csv(
    "../data/processed/payment_fact.csv"
)

In [24]:
insurance_master["Policy Start Date"] = pd.to_datetime(
    insurance_master["Policy Start Date"]
)

insurance_master["Policy End Date"] = pd.to_datetime(
    insurance_master["Policy End Date"]
)

claims_fact["Date of Claim"] = pd.to_datetime(
    claims_fact["Date of Claim"]
)

claims_fact["Settlement Date"] = pd.to_datetime(
    claims_fact["Settlement Date"]
)

payment_fact["Date of Payment"] = pd.to_datetime(
    payment_fact["Date of Payment"]
)

In [2]:
# Executive KPI Calculations

# KPI 1 Total Policies

total_policies = insurance_master["Policy ID"].nunique()

print(total_policies)

5000

In [4]:
# KPI 2 Total Customers

total_customers = insurance_master["Customer ID"].nunique()

print(total_customers)

5000

In [5]:
# KPI 3 Total Premium Revenue

total_premium = insurance_master[
    "Premium Amount"
].sum()

print(total_premium)

5261008.399999999

In [6]:
# KPI 4 — Total Coverage Amount

total_coverage = insurance_master[
    "Coverage Amount"
].sum()

print(total_coverage)

1272814747.0

In [7]:
# KPI 5 — Total Claim Amount

total_claim_amount = claims_fact[
    "Claim Amount"
].sum()

print(total_claim_amount)

251378846

In [8]:
# KPI 6 - Total Payment Collected

total_payment_collected = payment_fact[
    payment_fact["Payment Status"]=="Successful"
]["Amount Paid"].sum()

print(total_payment_collected)

1936819.46

In [9]:
# KPI 7 - Active Policies

active_policies = insurance_master[
    insurance_master["Status"]=="Active"
].shape[0]

print(active_policies)

1682

In [10]:
# KPI 8 - Active Policy %

active_policy_pct = round(
    (active_policies / total_policies)*100,
    2
)

print(active_policy_pct)

33.64

In [28]:
# KPI 9 - Policies Expiring This Year

current_year = pd.Timestamp.today().year

expiring_this_year = insurance_master[
    insurance_master["Policy End Date"].dt.year == current_year
].shape[0]

print(
    f"Policies Expiring This Year: {expiring_this_year}"
)

Policies Expiring This Year: 453

In [29]:
# KPI 10 - Renewal Rate%

renewed = insurance_master[
    insurance_master["Renewal Status"]=="Renewed"
].shape[0]

renewal_rate = round(
    (renewed / total_policies)*100,
    2
)

print(renewal_rate)

33.36

In [30]:
## Customer Analytics KPIs

# Age Bucket Wise Policies

age_bucket_kpi = insurance_master.groupby(
    "Age Bucket"
)["Policy ID"].count().reset_index()

age_bucket_kpi

  Age Bucket  Policy ID
0      18-25        572
1      26-35        805
2      36-45        706
3      46-55        737
4        56+       2180

In [31]:
# Gender Wise Policies

gender_kpi = insurance_master.groupby(
    "Gender"
)["Policy ID"].count().reset_index()

gender_kpi

   Gender  Policy ID
0  Female       1624
1    Male       1677
2   Other       1699

In [32]:
# Occupation Wise Policies

occupation_kpi = insurance_master.groupby(
    "Occupation"
)["Policy ID"].count().reset_index()

occupation_kpi

                           Occupation  Policy ID
0                  Academic librarian          6
1               Accommodation manager          8
2               Accountant, chartered          6
3     Accountant, chartered certified          7
4    Accountant, chartered management          1
..                                ...        ...
634           Water quality scientist          8
635                      Web designer          6
636                Wellsite geologist         10
637                            Writer         11
638                      Youth worker          5

[639 rows x 2 columns]

In [35]:
# Marital Status Wise Policies

marital_kpi = insurance_master.groupby(
    "Marital Status"
)["Policy ID"].count().reset_index()

marital_kpi

  Marital Status  Policy ID
0       Divorced       1263
1        Married       1273
2         Single       1266
3        Widowed       1198

In [36]:
## Policy Analytics KPIs

# Policy Type Wise Policy Count

policy_type_kpi = insurance_master.groupby(
    "Policy Type"
)["Policy ID"].count().reset_index()

policy_type_kpi

  Policy Type  Policy ID
0        Auto       1214
1      Health       1316
2        Life       1234
3    Property       1236

In [37]:
# Policy Status Distribution

policy_status_kpi = insurance_master.groupby(
    "Status"
)["Policy ID"].count().reset_index()

policy_status_kpi

       Status  Policy ID
0      Active       1682
1      Lapsed       1640
2  Terminated       1678

In [38]:
# Premium by Policy Type

premium_policy_type = insurance_master.groupby(
    "Policy Type"
)["Premium Amount"].sum().reset_index()

premium_policy_type

  Policy Type  Premium Amount
0        Auto      1250378.87
1      Health      1363452.53
2        Life      1339028.42
3    Property      1308148.58

In [39]:
## Claims Analytics KPIs

#Claim Status Wise Count

claim_status_kpi = claims_fact.groupby(
    "Claim Status"
)["Claim ID"].count().reset_index()

claim_status_kpi

  Claim Status  Claim ID
0     Approved      1712
1       Denied      1638
2      Pending      1650

In [40]:
# Claim Amount by Status

claim_amount_status = claims_fact.groupby(
    "Claim Status"
)["Claim Amount"].sum().reset_index()

claim_amount_status

  Claim Status  Claim Amount
0     Approved      85795878
1       Denied      83830362
2      Pending      81752606

In [41]:
# Average Claim Amount

avg_claim_amount = round(
    claims_fact["Claim Amount"].mean(),
    2
)

print(avg_claim_amount)

50275.77

In [42]:
# Average Settlement Days

avg_settlement_days = round(
    claims_fact["Settlement Days"].mean(),
    2
)

print(avg_settlement_days)

50.12

In [43]:
## Payment Analytics KPIs

# Payment Status Count

payment_status_kpi = payment_fact.groupby(
    "Payment Status"
)["Payment ID"].count().reset_index()

payment_status_kpi

  Payment Status  Payment ID
0         Failed        2484
1     Successful        2516

In [44]:
# Payment Method Analysis

payment_method_kpi = payment_fact.groupby(
    "Payment Method"
)["Payment ID"].count().reset_index()

payment_method_kpi

  Payment Method  Payment ID
0  Bank Transfer        1645
1           Cash        1744
2    Credit Card        1611

In [45]:
# Payment Success Rate

successful_payments = payment_fact[
    payment_fact["Payment Status"]=="Successful"
].shape[0]

payment_success_rate = round(
    (successful_payments / len(payment_fact))*100,
    2
)

print(payment_success_rate)

50.32

In [46]:
## Risk Analytics KPIs

# Risk Category Distribution

risk_kpi = insurance_master.groupby(
    "Risk Category"
)["Policy ID"].count().reset_index()

risk_kpi

  Risk Category  Policy ID
0     High Risk       1994
1      Low Risk       1492
2   Medium Risk       1514

In [47]:
# High Risk Policies

high_risk_count = insurance_master[
    insurance_master["Risk Category"]=="High Risk"
].shape[0]

print(high_risk_count)

1994

In [48]:
# Risk vs Renewal

risk_renewal = pd.crosstab(
    insurance_master["Risk Category"],
    insurance_master["Renewal Status"]
)

risk_renewal

Renewal Status  Not Renewed  Pending  Renewed
Risk Category
High Risk               667      655      672
Low Risk                519      473      500
Medium Risk             499      519      496

In [57]:
## Executive Insurance KPIs

# Claim Ratio %

claim_ratio = round(
    (total_claim_amount /
     total_premium)*100,
    2
)

print(claim_ratio)

4778.15

In [50]:
# Average Premium Per Policy

avg_premium = round(
    total_premium /
    total_policies,
    2
)

print(avg_premium)

1052.2

In [51]:
# Average Coverage Per Policy

avg_coverage = round(
    total_coverage /
    total_policies,
    2
)

print(avg_coverage)

254562.95

In [52]:
## Executive KPI Summary Table

executive_kpis = pd.DataFrame({
    "KPI":[
        "Total Policies",
        "Total Customers",
        "Total Premium Revenue",
        "Total Claim Amount",
        "Claim Ratio %",
        "Active Policy %",
        "Renewal Rate %",
        "Payment Success Rate %"
    ],
    "Value":[
        total_policies,
        total_customers,
        total_premium,
        total_claim_amount,
        claim_ratio,
        active_policy_pct,
        renewal_rate,
        payment_success_rate
    ]
})

executive_kpis

                      KPI         Value
0          Total Policies  5.000000e+03
1         Total Customers  5.000000e+03
2   Total Premium Revenue  5.261008e+06
3      Total Claim Amount  2.513788e+08
4           Claim Ratio %  4.778150e+03
5         Active Policy %  3.364000e+01
6          Renewal Rate %  3.336000e+01
7  Payment Success Rate %  5.032000e+01

In [53]:
# Export KPI Tables

executive_kpis.to_excel(
    "../data/reports/kpi_summary.xlsx",
    index=False
)

In [54]:
executive_kpis.to_csv(
    "../data/reports/executive_kpi_dashboard_table.csv",
    index=False
)

In [55]:
print("Total Policies:", total_policies)

print("Total Customers:", total_customers)

print("Total Premium Revenue:", total_premium)

print("Total Claim Amount:", total_claim_amount)

print("Claim Ratio %:", claim_ratio)

print("Active Policy %:", active_policy_pct)

print("Renewal Rate %:", renewal_rate)

print("Payment Success Rate %:", payment_success_rate)

print("Average Premium:", avg_premium)

print("Average Coverage:", avg_coverage)

Total Policies: 5000
Total Customers: 5000
Total Premium Revenue: 5261008.399999999
Total Claim Amount: 251378846
Claim Ratio %: 4778.15
Active Policy %: 33.64
Renewal Rate %: 33.36
Payment Success Rate %: 50.32
Average Premium: 1052.2
Average Coverage: 254562.95

In [58]:
insurance_master.shape

(6852, 30)

In [59]:
insurance_master["Policy Type"].isnull().sum()

np.int64(1852)

In [60]:
insurance_master[
    insurance_master["Policy Type"].isnull()
].head()

,Customer ID,Name,Gender,Age,Occupation,Marital Status,"Address (City, State, Zip Code)",Age Bucket,Married Flag,Senior Citizen Flag,...,Policy Duration Category,Active Policy Flag,Agent ID,Renewal Status,Policy Discounts,Risk Score,High_Risk_Flag,Risk Category,High Risk Flag,Renewal Segment
2,CUST78641469,Dr. Stephanie Collins,Other,79,"Buyer, retail",Widowed,"Thomasville, Minnesota, 57408",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CUST06110068,Gary Nielsen,Other,68,"Engineer, electronics",Divorced,"Seanfurt, Massachusetts, 75952",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CUST52268424,Clinton Underwood,Other,63,Amenity horticulturist,Single,"Thomasland, Utah, 99801",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,CUST31531027,Chase Johnson,Female,39,Catering manager,Divorced,"Masseyhaven, Louisiana, 68893",36-45,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,CUST40782869,Sarah Jacobson,Other,27,Theme park manager,Single,"Rileymouth, New York, 87040",26-35,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
insurance_master["Policy ID"].isnull().sum()

np.int64(1852)

In [62]:
insurance_reporting = insurance_master[
    insurance_master["Policy ID"].notnull()
].copy()

In [63]:
insurance_reporting.shape

(5000, 30)

In [64]:
insurance_reporting.to_csv(
    "../data/processed/insurance_reporting_dataset.csv",
    index=False
)

In [65]:
print(
    insurance_master["Policy ID"].isnull().sum()
)

print(
    insurance_master["Policy Type"].isnull().sum()
)

print(
    insurance_master["Premium Amount"].isnull().sum()
)

1852
1852
1852

In [66]:
insurance_reporting = insurance_master[
    insurance_master["Policy ID"].notnull()
].copy()

In [67]:
insurance_reporting.shape

(5000, 30)

In [68]:
insurance_master["Policy ID"].dtype

dtype('O')

In [69]:
insurance_master["Policy ID"].unique()[:20]

array(['POL10637039', 'POL30067784', nan, 'POL32316303', 'POL60672344',
       'POL70199824', 'POL25630495', 'POL02911863', 'POL24987681',
       'POL65820287', 'POL71626215', 'POL91190170', 'POL97881363',
       'POL29228697', 'POL35328184', 'POL98955756', 'POL73942223',
       'POL53660854', 'POL49945378', 'POL70863328'], dtype=object)

In [70]:
insurance_master["Policy ID"].isna().sum()

np.int64(1852)

In [71]:
insurance_master["Policy ID"].eq("").sum()

np.int64(0)

In [72]:
insurance_master["Policy ID"].astype(str).str.strip().eq("").sum()

np.int64(0)

In [73]:
insurance_master[
    insurance_master["Policy ID"].isna()
].head()

,Customer ID,Name,Gender,Age,Occupation,Marital Status,"Address (City, State, Zip Code)",Age Bucket,Married Flag,Senior Citizen Flag,...,Policy Duration Category,Active Policy Flag,Agent ID,Renewal Status,Policy Discounts,Risk Score,High_Risk_Flag,Risk Category,High Risk Flag,Renewal Segment
2,CUST78641469,Dr. Stephanie Collins,Other,79,"Buyer, retail",Widowed,"Thomasville, Minnesota, 57408",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CUST06110068,Gary Nielsen,Other,68,"Engineer, electronics",Divorced,"Seanfurt, Massachusetts, 75952",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CUST52268424,Clinton Underwood,Other,63,Amenity horticulturist,Single,"Thomasland, Utah, 99801",56+,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,CUST31531027,Chase Johnson,Female,39,Catering manager,Divorced,"Masseyhaven, Louisiana, 68893",36-45,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,CUST40782869,Sarah Jacobson,Other,27,Theme park manager,Single,"Rileymouth, New York, 87040",26-35,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
insurance_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6852 entries, 0 to 6851
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Customer ID                      6852 non-null   object
 1   Name                             6852 non-null   object
 2   Gender                           6852 non-null   object
 3   Age                              6852 non-null   int64
 4   Occupation                       6852 non-null   object
 5   Marital Status                   6852 non-null   object
 6   Address (City, State, Zip Code)  6852 non-null   object
 7   Age Bucket                       6852 non-null   object
 8   Married Flag                     6852 non-null   int64
 9   Senior Citizen Flag              6852 non-null   int64
 10  Customer Segment                 6852 non-null   object
 11  Policy ID                        5000 non-null   object
 12  Policy Type                      5000 non-null   object
 13  Coverage Amount                  5000 non-null   float64
 14  Premium Amount                   5000 non-null   float64
 15  Policy Start Date                5000 non-null   datetime64[ns]
 16  Policy End Date                  5000 non-null   datetime64[ns]
 17  Payment Frequency                5000 non-null   object
 18  Status                           5000 non-null   object
 19  Policy Duration Days             5000 non-null   float64
 20  Policy Duration Category         5000 non-null   object
 21  Active Policy Flag               5000 non-null   float64
 22  Agent ID                         5000 non-null   object
 23  Renewal Status                   5000 non-null   object
 24  Policy Discounts                 5000 non-null   float64
 25  Risk Score                       5000 non-null   float64
 26  High_Risk_Flag                   5000 non-null   float64
 27  Risk Category                    5000 non-null   object
 28  High Risk Flag                   5000 non-null   float64
 29  Renewal Segment                  5000 non-null   object
dtypes: datetime64[ns](2), float64(8), int64(3), object(17)
memory usage: 1.6+ MB

In [77]:
insurance_reporting = (
    insurance_master[
        insurance_master["Policy ID"].notna()
    ]
    .copy()
)

print("Rows:", insurance_reporting.shape[0])

print(
    "Null Policy IDs:",
    insurance_reporting["Policy ID"]
    .isna()
    .sum()
)

Rows: 5000
Null Policy IDs: 0

In [78]:
print(insurance_master.shape)

print(
    insurance_master["Policy ID"].isna().sum()
)

insurance_reporting = (
    insurance_master[
        insurance_master["Policy ID"].notna()
    ]
)

print(insurance_reporting.shape)

(6852, 30)
1852
(5000, 30)